language: node_js
node_js:
  - "15"
  - "14"
  - "12"
  - "10"
os:
  - linux
  - osx
dist: bionic
sudo: false
install:
  - g++ --version
  - npm --version
  - npm install
  - wc -l src/parser.c
  - wc -c build/Release/*.node
script:
  - npm test
  - bash bin/get-uvm.sh
  - node bin/test-uvm.js
